Chore/various improvements
DanJFletcher/vue-model-factories pull request #6
Opened 2018-12-07 18:40 UTC by jakeklassen

Some various _improvements_ depending on who you ask maybe haha.

* Cleaned up some styling. There where inconsistencies all over the place so I added prettier.
* `.npmignore` to ignore the `src` code since `lib` is published.
* Removed `lib` from cache and now ignore it since it's only relevant to npm.
* Added `prepublish` script to run for npm release.

Some changes to the `index.js` file were just to take better advantage of a closure and avoid `let` where possible. I think more can be done but I just did a quick once over.

2018-12-07 19:07 UTC, jakeklassen commented
Switched to `prepublishOnly` since `prepublish` is also run on local npm install.

2018-12-07 19:13 UTC, jakeklassen commented
Drop node v7 to stick with LTS releases and address yarn incompatibility:

Travis error log:
```
warning You are using Node "7.10.1" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
```

2018-12-07 21:18 UTC, DanJFletcher commented on .prettierrc
> +  "trailingComma": "none"
trailing commas make for less changed lines in git which is why I use them.

2018-12-07 21:18 UTC, DanJFletcher commented on .prettierrc
> +  "semi": true,
I prefer having semi set to false.

2018-12-07 21:23 UTC, DanJFletcher requested changes
This is awesome! There was some seriously much-needed clean up in this repo haha 😅

I do prefer no semi-colons and trailing commas so we'll just have to update the style rules for that. Otherwise, this looks great! Thanks for the cleanup 👍

2018-12-10 16:55 UTC, jakeklassen commented
@DanJFletcher Made those stylistic changes you like :+1:

2018-12-15 19:37 UTC, merged

2018-12-15 19:38 UTC, DanJFletcher commented
> @DanJFletcher Made those stylistic changes you like 👍

You the man!